Refactor and cleanup
simongranger/page-object-generator pull request #1
Opened 2018-05-25 19:09 UTC by TamimiGitHub

2018-05-25 19:11 UTC, TamimiGitHub commented on generator.rb
> +          file.puts("  " + node['name'].upcase.tr(" ", "_").tr("-", "_").tr(":", "") + " = { name: '" + node['name'] + "' }")
We need to do better xml parsing here

2018-05-28 13:59 UTC, simongranger commented on generator.rb
> +  file.puts("require_relative '../../../../Test/appium/common/page_helper'")
The path here should probably be a CONST

2018-05-28 14:03 UTC, simongranger commented on generator.rb
> -          out_file.puts("  " + node['name'].upcase.tr(" ", "_").tr("-", "_").tr(":", "") + " = { name: '" + node['name'] + "' }")
Should have a method that takes a string and returns it with all these characters replaced.

2018-05-28 14:04 UTC, simongranger commented on generator.rb
> -          out_file.puts("  " + node['name'].upcase.tr(" ", "_").tr("-", "_").tr(":", "") + " = { name: '" + node['name'] + "' }")
tr(" ", "_").tr("-", "_").tr(":", "")

2018-05-29 19:11 UTC, simongranger requested changes

2018-05-29 19:11 UTC, simongranger commented on generator.rb
> +          file.puts("  def click_#{var_name}")
var_name.downcase

2018-05-29 19:11 UTC, simongranger commented on generator.rb
> +          file.puts("  def #{var_name}_displayed?")
var_name.downcase

2018-05-29 19:11 UTC, simongranger commented on generator.rb
> +def populate_click_methods file, doc
add driver as a parameter

2018-05-29 19:11 UTC, simongranger commented on generator.rb
> +def populate_locators file, doc
Add driver as parameter

2018-05-29 19:11 UTC, simongranger commented on generator.rb
> +def populate_display_methods file, doc
Add driver as parameter

2018-05-29 19:11 UTC, simongranger commented on generator.rb
>          elements = @driver.find_elements(name: node['name'])
Replace @driver with driver everwhere it's used

2018-05-29 19:11 UTC, simongranger commented on generator.rb
> +    populate_locators(page_file, doc)
Add driver as a parameter

2018-05-29 19:11 UTC, simongranger commented on generator.rb
> +    populate_display_methods(page_file, doc)
Add driver as a parameter

2018-05-29 19:11 UTC, simongranger commented on generator.rb
> +    populate_click_methods(page_file, doc)
Add driver as a parameter

2018-05-29 19:29 UTC, simongranger approved these changes

2018-05-29 19:30 UTC, merged